#pragma once
#define ENTITIES_MAX 100
#define COMPONENTS_MAX 200
#define COMPONENT_TYPES_MAX 10
#define FIELDS_IN_COMPONENT_MAX 20
#define SYSTEMS_MAX 20



#define INT_FIELDS_MAX 200
#define FLOAT_FIELDS_MAX 200
#define STRING_FIELDS_MAX 200
